# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-07-06 13:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('persons', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='person',
        ),
    ]
